解决Nukkit数据库链接异常NPE问题 & 配置数据库连接开关
DreamVoid/MiraiMC pull request #123
Opened 2022-02-17 14:42 UTC by zixuan2020

2022-02-17 15:34 UTC, DreamVoid commented on MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/internal/Utils.java
> +        if(connection != null)
if语句末尾可以加个大括号，美观，方便我收起代码，不过加不加都无所谓

2022-02-17 15:36 UTC, DreamVoid approved these changes

2022-02-17 15:56 UTC, zixuan2020 commented on MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/internal/Utils.java
> +        if(connection != null)
还有其他问题吗？

2022-03-20 15:56 UTC, DreamVoid requested changes
一个PR只添加一个功能
请分离后重新开PR

另外，复查后认为关闭数据库功能不符合未来的开发计划。暂不考虑添加。

2022-03-20 15:56 UTC, closed without merging