转换为 Gradle 项目
DreamVoid/MiraiMC pull request #197
Opened 2022-07-07 16:12 UTC by MrXiaoM

review please

2022-07-08 00:27 UTC, MrXiaoM commented
> 我用maven是为了发到maven中央仓库，你把它给我移了，我用什么
> （好像还想到点别的，结果忘了）
> 
> 弄好后建议给出几个能说服我的理由让我换成gradle

gradle也是能发布到maven中心仓库的，这是我把这个pr设为草稿的其中一个原因。目前只搬了基础支持，还没完全弄好。

2022-07-08 17:17 UTC, MrXiaoM commented
使用 Gradle
* 灵活性更强
* 使用 Kotlin DSL，几乎就是通过写脚本来进行编译
* 在没有 IDE 的情况下可以使用 gradlew 进行构建操作
* 不用第三方插件的情况下解决了这个问题→ `<!-- 提醒：记得去Sponge和Velocity手动修改 -->`
* 我想不到了，大约就这么多

## 指南

在当前 PR 中，控制台执行 (或在 IDEA 新建 Gradle 运行配置，在*任务和实参*处填写，但省略 `gradlew `)
* `gradlew buildUp` 构建所有子模块 (包括打包依赖、javadoc、源jar)
* `gradlew shadowJar` 构建所有子模块 (包括打包依赖)
* `gradlew 子模块名称:shadowJar` 构建某个子模块 (包括打包依赖)
* `gradlew javadocJar子模块简称` 构建某个子模块的 javadoc 并输出jar
* `gradlew sourceJar子模块简称` 输出某个子模块的源 jar
> e.g
> `gradlew MiraiMC-Bukkit:shadowJar`  
> `gradlew javadocJarBukkit`  
> `gradlew sourceJarBukkit`  

## 注意事项
当前 PR 的*文件夹名称*即*子模块名称*，短杠后面的名称即简称，经过我的调整，所有打包构建都会输出到 `/build/libs/`

已测试可在构建后执行 `gradlew publishToMavenLocal` 成功发布所有模块到本地仓库，  
单独发布子模块详见任务 `publish子模块名称PublicationTo仓库名称`。

要将所有模块发布到中央仓库，应执行任务 `publishAllPublicationsToSonatypeRepositoryRepository`

发布任务**仅为发布任务**，应当在构建完毕后再进行发布。

尽量不要在 IDEA 里的 Gradle 侧栏点开子模块执行任务，我试过 IDEA 会把子模块当作父模块来执行任务，导致读不到依赖的模块 MiraiMC-Base，直接跑控制台命令是没问题的。

2022-07-09 04:30 UTC, DreamVoid commented
灵活性更强体现在何处：我每次打开Gradle项目都要下载一次src，而下载src要等好久且不和我的无线网卡兼容
我不喜欢在任何一个Minecraft服务端相关的项目使用kotlin，项目是否需要依赖kotlin？
是否完整编译过一次，插件大小和我近期发布的预发行版所有文件的大小差距是否在300kb以内？
使用maven我能只用maven package生成所有构建后的jar且不会生成javadoc等其他用不到的内容，maven deploy能一次生成所有发布到maven中央仓库用到的所有jar且能一次成功，基本做到无人值守，gradle是否也能这样？（所有操作全部在IDEA里，不使用控制台）

2022-07-09 04:32 UTC, DreamVoid commented on MiraiMC-Bukkit/build.gradle.kts
> +        exclude { it.moduleGroup.startsWith("org.jetbrains.kotlin") }
在maven中我从来没有考虑过kotlin相关的库，那么这两行为什么会出现

2022-07-09 04:35 UTC, DreamVoid commented on build.gradle.kts
> +}
我看了一遍官方的文档，我认为你应该重写这部分发布到maven中央仓库的内容。

2022-07-09 05:28 UTC, MrXiaoM commented
> * 灵活性更强体现在何处？（我每次打开Gradle项目都要下载一次src，而下载src要等好久且不和我的无线网卡兼容）
> * 我不喜欢在任何一个Minecraft服务端相关的项目使用kotlin，项目是否需要依赖kotlin？
> * 是否完整编译过一次，插件大小和我近期发布的预发行版所有文件的大小差距是否在300kb以内？
> * 使用maven我能只用maven package生成所有构建后的jar且不会生成javadoc等其他用不到的内容，maven deploy能一次生成所有发布到maven中央仓库用到的所有jar且能一次成功，基本做到无人值守，gradle是否也能这样？（所有操作全部在IDEA里，不使用控制台）

* 在首次配置将所有依赖缓存完毕后，我每次打开仅需扫描一次依赖索引，除非构建脚本变动或缓存被清理，无需再下载
* 我使用 Gradle Kotlin DSL 时的个人习惯，一会改成 java
* 经过对比，打包进去的库比你的发行版有些许差异，经过检查是我没开 minimize 把不必要的类也打进去了
* 在 IDEA 新建 Gradle 运行配置，*Gradle 项目* 填 `MiraiMC`，*任务和实参* 填写
  * `shadowJar` 生成所有构建，且不会生成 javadoc 等其他用不到的内容
  * `clean buildUp publishAllPublicationsToSonatypeRepositoryRepository` 清理并生成所有构建包括 javadoc 和 source，并发布到中央仓库

2022-07-09 05:31 UTC, MrXiaoM commented on MiraiMC-Bukkit/build.gradle.kts
> +        exclude { it.moduleGroup.startsWith("org.jetbrains.kotlin") }
已移除 kotlin jvm 插件，下一次提交时删除

2022-07-09 05:33 UTC, DreamVoid commented
> > * 灵活性更强体现在何处？（我每次打开Gradle项目都要下载一次src，而下载src要等好久且不和我的无线网卡兼容）
> > * 我不喜欢在任何一个Minecraft服务端相关的项目使用kotlin，项目是否需要依赖kotlin？
> > * 是否完整编译过一次，插件大小和我近期发布的预发行版所有文件的大小差距是否在300kb以内？
> > * 使用maven我能只用maven package生成所有构建后的jar且不会生成javadoc等其他用不到的内容，maven deploy能一次生成所有发布到maven中央仓库用到的所有jar且能一次成功，基本做到无人值守，gradle是否也能这样？（所有操作全部在IDEA里，不使用控制台）
> 
> * 在首次配置将所有依赖缓存完毕后，我每次打开仅需扫描一次依赖索引，除非构建脚本变动或缓存被清理，无需再下载
> * 我使用 Gradle Kotlin DSL 时的个人习惯，一会改成 java
> * 经过对比，打包进去的库比你的发行版有些许差异，经过检查是我没开 minimize 把不必要的类也打进去了
> * 在 IDEA 新建 Gradle 运行配置，_Gradle 项目_ 填 `MiraiMC`，_任务和实参_ 填写
>   
>   * `shadowJar` 生成所有构建，且不会生成 javadoc 等其他用不到的内容
>   * `clean buildUp publishAllPublicationsToSonatypeRepositoryRepository` 清理并生成所有构建包括 javadoc 和 source，并发布到中央仓库

顺便测试一下在Bukkit、Bungee等平台是否工作正常

2022-07-09 06:50 UTC, MrXiaoM commented
TODO：看了下帮助文档，为了能正常引用 `MiraiMC-Integration` 来进行开发，我还应该在发布的 pom 中声明依赖。

2022-07-09 13:58 UTC, DreamVoid requested changes

2022-07-09 13:58 UTC, DreamVoid commented on MiraiMC-Velocity/src/main/templates/me/dreamvoid/miraimc/velocity/BuildConstants.java
> +package me.dreamvoid.miraimc.velocity;
放到utils包

2022-07-09 13:58 UTC, DreamVoid commented on MiraiMC-Sponge/src/main/templates/me/dreamvoid/miraimc/sponge/BuildConstants.java
> +package me.dreamvoid.miraimc.sponge;
放到utils包

2022-07-09 14:00 UTC, DreamVoid commented
> > * 灵活性更强体现在何处？（我每次打开Gradle项目都要下载一次src，而下载src要等好久且不和我的无线网卡兼容）
> > * 我不喜欢在任何一个Minecraft服务端相关的项目使用kotlin，项目是否需要依赖kotlin？
> > * 是否完整编译过一次，插件大小和我近期发布的预发行版所有文件的大小差距是否在300kb以内？
> > * 使用maven我能只用maven package生成所有构建后的jar且不会生成javadoc等其他用不到的内容，maven deploy能一次生成所有发布到maven中央仓库用到的所有jar且能一次成功，基本做到无人值守，gradle是否也能这样？（所有操作全部在IDEA里，不使用控制台）
> 
> * 在首次配置将所有依赖缓存完毕后，我每次打开仅需扫描一次依赖索引，除非构建脚本变动或缓存被清理，无需再下载
> * 我使用 Gradle Kotlin DSL 时的个人习惯，一会改成 java
> * 经过对比，打包进去的库比你的发行版有些许差异，经过检查是我没开 minimize 把不必要的类也打进去了
> * 在 IDEA 新建 Gradle 运行配置，_Gradle 项目_ 填 `MiraiMC`，_任务和实参_ 填写
>   
>   * `shadowJar` 生成所有构建，且不会生成 javadoc 等其他用不到的内容
>   * `clean buildUp publishAllPublicationsToSonatypeRepositoryRepository` 清理并生成所有构建包括 javadoc 和 source，并发布到中央仓库

第一点好像maven也是这样的，除了这个还有别的体现吗

2022-07-09 14:05 UTC, MrXiaoM commented on MiraiMC-Velocity/src/main/templates/me/dreamvoid/miraimc/velocity/BuildConstants.java
> +package me.dreamvoid.miraimc.velocity;
kk

2022-07-09 14:05 UTC, MrXiaoM commented on MiraiMC-Sponge/src/main/templates/me/dreamvoid/miraimc/sponge/BuildConstants.java
> +package me.dreamvoid.miraimc.sponge;
kk

2022-07-09 14:08 UTC, MrXiaoM commented
> 第一点好像maven也是这样的，除了这个还有别的体现吗

gradle 使用的是构建脚本，可以自行编写代码实现构建过程中的操作。maven 使用是配置文件，据 Gradle 说法是 「maven 提供了一个非常严格的模型，使自定义变得乏味」，详见 [Gradle vs Maven Comparison](https://gradle.org/maven-vs-gradle/)

2022-07-11 15:02 UTC, DreamVoid commented
最好在13号前弄好，13号我要发版

2022-07-11 15:05 UTC, DreamVoid commented on build.gradle.kts
> +        compileOnly("net.mamoe:mirai-console:$miraiVersion:all")
为何加上这个库？

2022-07-11 15:21 UTC, DreamVoid commented on build.gradle.kts
> +        mavenCentral()
中央仓库优先，其次是本地仓库，不要任何镜像站

2022-07-11 16:18 UTC, MrXiaoM commented
或许是我技艺不精，我在各种兼容性问题下兜兜转转使用了我并不常用的 Kotlin DSL 进行编写脚本，我从一开始认为迁移或许并不是非常困难直到开始各种堆 sh1t 山，甚至没有想到用 buildSrc。gradle 确实是更灵活，但编写脚本和如何优化也更困难。也许现在维持现状，是较好的选择。最后祝你有愉快的一天。

2022-07-11 16:18 UTC, closed without merging