优化nukkit版命令 (1/3)
DreamVoid/MiraiMC pull request #65
Opened 2021-12-16 12:40 UTC by lt-name

利用若水的工具类优化nukkit版命令，实现命令枚举
![截图20211216203730](https://user-images.githubusercontent.com/45508179/146373816-ff0c9757-83ff-463d-b71d-049eb0d4573b.png)

2021-12-16 15:25 UTC, DreamVoid commented on MiraiMC-Nukkit/src/main/java/me/dreamvoid/miraimc/nukkit/NukkitPlugin.java
> +
注册命令放在加载自动登录机器人操作的后面，像 [Bukkit 版本](https://github.com/DreamVoid/MiraiMC/blob/717f99d8514571a68955f55cb57e2df2eb8f76d1/MiraiMC-Bukkit/src/main/java/me/dreamvoid/miraimc/bukkit/BukkitPlugin.java#L69-L71)一样。再加个提示信息。

2021-12-16 15:25 UTC, DreamVoid commented on MiraiMC-Nukkit/src/main/java/me/dreamvoid/miraimc/nukkit/commands/MiraiVerifyCommand.java
> +        //TODO
miraiverify 本来就不是正常使用时会用到的命令，所以直接留空即可。

2021-12-17 05:09 UTC, DreamVoid requested changes

2021-12-17 05:09 UTC, DreamVoid commented on MiraiMC-Nukkit/src/main/java/me/dreamvoid/miraimc/nukkit/NukkitPlugin.java
> +
```
> miraiverify
13:07:11 [INFO ] Unknown command. Try /help for a list of commands
```

2021-12-17 05:11 UTC, DreamVoid commented on MiraiMC-Nukkit/src/main/java/me/dreamvoid/miraimc/nukkit/NukkitPlugin.java
>  import java.sql.SQLException;
没用到的库去掉

2021-12-17 10:30 UTC, lt-name commented
最近时间不是很充足，写的有点赶

2021-12-17 15:00 UTC, DreamVoid approved these changes

2021-12-17 15:04 UTC, merged